import { chunkArray } from '@atproto/common-web'
import { SeedClient } from './client'

export default async (sc: SeedClient, max = Infinity) => {
  // @TODO when these are run in parallel, seem to get an intermittent
  // "TypeError: fetch failed" while running the tests.
  const userSubset = users.slice(0, Math.min(max, users.length))
  const chunks = chunkArray(userSubset, 50)
  for (const chunk of chunks) {
    await Promise.all(
      chunk.map(async (user) => {
        const { handle, displayName } = user
        await sc.createAccount(handle, {
          handle: handle,
          password: 'password',
          email: `${handle}@bsky.app`,
        })
        if (displayName !== null) {
          await sc.createProfile(sc.dids[handle], displayName, '')
        }
      }),
    )
  }
  return sc
}

const users = [
  { handle: 'silas77.sfproject.net', displayName: 'Tanya Denesik' },
  { handle: 'nicolas-krajcik10.sfproject.net', displayName: null },
  { handle: 'lennie-strosin.sfproject.net', displayName: null },
  { handle: 'aliya-hodkiewicz.sfproject.net', displayName: 'Carlton Abernathy IV' },
  { handle: 'jeffrey-sawayn87.sfproject.net', displayName: 'Patrick Sawayn' },
  { handle: 'kaycee66.sfproject.net', displayName: null },
  { handle: 'adrienne49.sfproject.net', displayName: 'Kim Streich' },
  { handle: 'magnus53.sfproject.net', displayName: 'Sally Funk' },
  { handle: 'charles-spencer.sfproject.net', displayName: null },
  { handle: 'elta48.sfproject.net', displayName: 'Dr. Lowell DuBuque' },
  { handle: 'tressa-senger.sfproject.net', displayName: null },
  { handle: 'marietta-zboncak.sfproject.net', displayName: null },
  { handle: 'alexander-hickle.sfproject.net', displayName: 'Winifred Harber' },
  { handle: 'rodger-maggio24.sfproject.net', displayName: 'Yolanda VonRueden' },
  { handle: 'janiya48.sfproject.net', displayName: 'Miss Terrell Ziemann' },
  { handle: 'cayla-marquardt39.sfproject.net', displayName: 'Rachel Kshlerin' },
  { handle: 'jonathan-green.sfproject.net', displayName: 'Erica Mertz' },
  { handle: 'brycen-smith.sfproject.net', displayName: null },
  { handle: 'leonel-koch43.sfproject.net', displayName: 'Karl Bosco IV' },
  { handle: 'fidel-rath.sfproject.net', displayName: null },
  { handle: 'raleigh-metz.sfproject.net', displayName: null },
  { handle: 'kim41.sfproject.net', displayName: null },
  { handle: 'roderick-dibbert.sfproject.net', displayName: null },
  { handle: 'alec-bergnaum.sfproject.net', displayName: 'Cody Berge' },
  { handle: 'sven70.sfproject.net', displayName: null },
  { handle: 'ola-oconnell.sfproject.net', displayName: null },
  { handle: 'chauncey-klein.sfproject.net', displayName: 'Kelvin Klein' },
  { handle: 'ariel-krajcik.sfproject.net', displayName: null },
  { handle: 'murphy35.sfproject.net', displayName: 'Mrs. Clifford Mertz' },
  { handle: 'joshuah-parker11.sfproject.net', displayName: null },
  { handle: 'dewitt-wunsch.sfproject.net', displayName: null },
  { handle: 'kelton-nitzsche43.sfproject.net', displayName: null },
  { handle: 'dock-mann91.sfproject.net', displayName: 'Miss Danielle Weber' },
  { handle: 'herman-gleichner95.sfproject.net', displayName: 'Kelli Schinner III' },
  { handle: 'gerda-marquardt.sfproject.net', displayName: 'Myron Wolf' },
  { handle: 'jamil-batz.sfproject.net', displayName: null },
  { handle: 'hilario84.sfproject.net', displayName: null },
  { handle: 'kayli-bode.sfproject.net', displayName: 'Miss Floyd McClure' },
  { handle: 'elouise28.sfproject.net', displayName: 'Alberta Fay' },
  { handle: 'leann49.sfproject.net', displayName: null },
  { handle: 'javon24.sfproject.net', displayName: null },
  { handle: 'polly-shanahan45.sfproject.net', displayName: null },
  { handle: 'rosamond38.sfproject.net', displayName: 'Karl Goyette' },
  { handle: 'fredrick-mueller.sfproject.net', displayName: null },
  { handle: 'reina-runte33.sfproject.net', displayName: 'Pablo Schmidt' },
  { handle: 'bianka33.sfproject.net', displayName: null },
  { handle: 'carlos6.sfproject.net', displayName: null },
  { handle: 'jermain-smith.sfproject.net', displayName: 'Eileen Stroman' },
  { handle: 'gina97.sfproject.net', displayName: null },
  { handle: 'kiera97.sfproject.net', displayName: null },
  { handle: 'savannah-botsford.sfproject.net', displayName: 'Darnell Kuvalis' },
  { handle: 'lilliana-waters.sfproject.net', displayName: null },
  { handle: 'hailey-stroman.sfproject.net', displayName: 'Elsa Schaden' },
  { handle: 'dortha-terry.sfproject.net', displayName: 'Nicole Bradtke' },
  { handle: 'hank-powlowski32.sfproject.net', displayName: null },
  { handle: 'ervin-daugherty.sfproject.net', displayName: null },
  { handle: 'nannie18.sfproject.net', displayName: null },
  { handle: 'gilberto-watsica65.sfproject.net', displayName: 'Ms. Ida Wilderman' },
  { handle: 'kara-zieme58.sfproject.net', displayName: 'Andres Towne' },
  { handle: 'crystal-boyle.sfproject.net', displayName: null },
  { handle: 'tobin63.sfproject.net', displayName: 'Alex Johnson' },
  { handle: 'isai-kunze72.sfproject.net', displayName: 'Marion Dickinson' },
  { handle: 'paris-swift.sfproject.net', displayName: null },
  { handle: 'nestor90.sfproject.net', displayName: 'Travis Hoppe' },
  { handle: 'aliyah-flatley12.sfproject.net', displayName: 'Loren Krajcik' },
  { handle: 'maiya42.sfproject.net', displayName: null },
  { handle: 'dovie33.sfproject.net', displayName: null },
  { handle: 'kendra-ledner80.sfproject.net', displayName: 'Sergio Hane' },
  { handle: 'greyson-tromp3.sfproject.net', displayName: null },
  { handle: 'precious-fay.sfproject.net', displayName: null },
  { handle: 'kiana-schmitt39.sfproject.net', displayName: null },
  { handle: 'rhianna-stamm29.sfproject.net', displayName: null },
  { handle: 'tiara-mohr.sfproject.net', displayName: null },
  { handle: 'eleazar-balist70.sfproject.net', displayName: 'Gordon Weissnat' },
  { handle: 'bettie-bogisich96.sfproject.net', displayName: null },
  { handle: 'lura-jacobi55.sfproject.net', displayName: null },
  { handle: 'santa-hermann78.sfproject.net', displayName: 'Melissa Johnson' },
  { handle: 'dylan61.sfproject.net', displayName: null },
  { handle: 'ryley-kerluke.sfproject.net', displayName: 'Alexander Purdy' },
  { handle: 'moises-bins8.sfproject.net', displayName: null },
  { handle: 'angelita-schaef27.sfproject.net', displayName: null },
  { handle: 'natasha83.sfproject.net', displayName: 'Dean Romaguera' },
  { handle: 'sydni48.sfproject.net', displayName: null },
  { handle: 'darrion91.sfproject.net', displayName: 'Jeanette Weimann' },
  { handle: 'reynold-ortiz.sfproject.net', displayName: null },
  { handle: 'hassie-schuppe.sfproject.net', displayName: 'Rita Zieme' },
  { handle: 'clark-stehr8.sfproject.net', displayName: 'Sammy Larkin' },
  { handle: 'preston-harris.sfproject.net', displayName: 'Ms. Bradford Thiel' },
  { handle: 'benedict-schulist.sfproject.net', displayName: 'Todd Stark' },
  { handle: 'alden-wolff22.sfproject.net', displayName: null },
  { handle: 'joel-gulgowski.sfproject.net', displayName: null },
  { handle: 'joanie56.sfproject.net', displayName: 'Ms. Darin Cole' },
  { handle: 'israel-hermann0.sfproject.net', displayName: 'Wilbur Schuster' },
  { handle: 'tracy56.sfproject.net', displayName: null },
  { handle: 'kyle72.sfproject.net', displayName: null },
  { handle: 'gunnar-dare70.sfproject.net', displayName: 'Mrs. Angelo Keeling' },
  { handle: 'justus58.sfproject.net', displayName: null },
  { handle: 'brooke24.sfproject.net', displayName: 'Clint Ward' },
  { handle: 'angela-morissette.sfproject.net', displayName: 'Jim Kertzmann' },
  { handle: 'amy-bins.sfproject.net', displayName: 'Angelina Hills' },
  { handle: 'susanna81.sfproject.net', displayName: null },
  { handle: 'jailyn-hettinger50.sfproject.net', displayName: 'Sheldon Ratke' },
  { handle: 'wendell-hansen54.sfproject.net', displayName: null },
  { handle: 'jennyfer-spinka.sfproject.net', displayName: 'Leticia Blick' },
  { handle: 'alexandrea31.sfproject.net', displayName: 'Leslie Von' },
  { handle: 'hazle-davis.sfproject.net', displayName: 'Ella Farrell' },
  { handle: 'alta6.sfproject.net', displayName: null },
  { handle: 'sherwood4.sfproject.net', displayName: 'Dr. Hattie Nienow I' },
  { handle: 'marilie24.sfproject.net', displayName: 'Gene Howell' },
  { handle: 'jimmie-feeney82.sfproject.net', displayName: null },
  { handle: 'trisha-ohara.sfproject.net', displayName: null },
  { handle: 'jake-schuster33.sfproject.net', displayName: 'Raymond Price' },
  { handle: 'shane-torphy52.sfproject.net', displayName: 'Sadie Carter' },
  { handle: 'nakia-kuphal8.sfproject.net', displayName: null },
  { handle: 'lea-trantow.sfproject.net', displayName: null },
  { handle: 'joel62.sfproject.net', displayName: 'Veronica Nitzsche' },
  { handle: 'roosevelt33.sfproject.net', displayName: 'Jay Moen' },
  { handle: 'talon-okeefe85.sfproject.net', displayName: null },
  { handle: 'herman-dare.sfproject.net', displayName: 'Eric White' },
  { handle: 'flavio-fay.sfproject.net', displayName: 'John Lindgren' },
  { handle: 'elyse-prosacco.sfproject.net', displayName: null },
  { handle: 'jessyca-wiegand23.sfproject.net', displayName: 'Debra Lockman' },
  { handle: 'ara-spencer41.sfproject.net', displayName: null },
  { handle: 'frederic-fadel.sfproject.net', displayName: null },
  { handle: 'zora-gerlach.sfproject.net', displayName: 'Noel Hansen' },
  { handle: 'spencer4.sfproject.net', displayName: 'Marjorie Gorczany' },
  { handle: 'gage-wilkinson33.sfproject.net', displayName: 'Preston Schoen V' },
  { handle: 'kiley-runolfsson1.sfproject.net', displayName: null },
  { handle: 'ramona80.sfproject.net', displayName: 'Sylvia Dietrich' },
  { handle: 'rashad97.sfproject.net', displayName: null },
  { handle: 'kylie76.sfproject.net', displayName: 'Josefina Pfeffer' },
  { handle: 'alisha-zieme.sfproject.net', displayName: null },
  { handle: 'claud79.sfproject.net', displayName: null },
  { handle: 'jairo-kuvalis.sfproject.net', displayName: 'Derrick Jacobson' },
  { handle: 'delfina-emard.sfproject.net', displayName: null },
  { handle: 'waino-gutmann20.sfproject.net', displayName: 'Wesley Kemmer' },
  { handle: 'arvid-hermiston49.sfproject.net', displayName: 'Vernon Towne PhD' },
  { handle: 'hans79.sfproject.net', displayName: 'Rex Hartmann' },
  { handle: 'karlee-greenholt40.sfproject.net', displayName: null },
  { handle: 'nels-cummings.sfproject.net', displayName: null },
  { handle: 'andrew-maggio.sfproject.net', displayName: null },
  { handle: 'stephany75.sfproject.net', displayName: null },
  { handle: 'alba-lueilwitz.sfproject.net', displayName: null },
  { handle: 'fermin47.sfproject.net', displayName: null },
  { handle: 'milo-quitzon3.sfproject.net', displayName: null },
  { handle: 'eudora-dietrich4.sfproject.net', displayName: 'Carol Littel' },
  { handle: 'uriel-witting12.sfproject.net', displayName: 'Sophia Schmidt' },
  { handle: 'reuben-stracke48.sfproject.net', displayName: 'Darrell Walker MD' },
  { handle: 'letitia-sawayn11.sfproject.net', displayName: 'Mrs. Sophie Reilly' },
  { handle: 'macy-schaden.sfproject.net', displayName: 'Lindsey Klein' },
  { handle: 'imelda61.sfproject.net', displayName: 'Shannon Beier' },
  { handle: 'oswald-bailey.sfproject.net', displayName: 'Angel Mann' },
  { handle: 'pattie-fisher34.sfproject.net', displayName: null },
  { handle: 'loyce95.sfproject.net', displayName: 'Claude Tromp' },
  { handle: 'melyna-zboncak.sfproject.net', displayName: null },
  { handle: 'rowan-parisian.sfproject.net', displayName: 'Mr. Veronica Feeney' },
  { handle: 'lois-blanda20.sfproject.net', displayName: 'Todd Rolfson' },
  { handle: 'turner-bali76.sfproject.net', displayName: null },
  { handle: 'dee-hoppe65.sfproject.net', displayName: null },
  { handle: 'nikko-rosenbaum60.sfproject.net', displayName: 'Joann Gutmann' },
  { handle: 'cornell-rom53.sfproject.net', displayName: null },
  { handle: 'zack3.sfproject.net', displayName: null },
  { handle: 'fredrick41.sfproject.net', displayName: 'Julius Kreiger' },
  { handle: 'elwyn62.sfproject.net', displayName: null },
  { handle: 'isaias-hirthe37.sfproject.net', displayName: 'Louis Cremin' },
  { handle: 'ronaldo36.sfproject.net', displayName: null },
  { handle: 'jesse34.sfproject.net', displayName: 'Bridget Schulist' },
  { handle: 'darrel-mills17.sfproject.net', displayName: null },
  { handle: 'euna-mayert92.sfproject.net', displayName: 'Grant Lang II' },
  { handle: 'terrell92.sfproject.net', displayName: null },
  { handle: 'alyson-bogisich.sfproject.net', displayName: 'Dana MacGyver' },
  { handle: 'nicolas65.sfproject.net', displayName: null },
  { handle: 'bernita8.sfproject.net', displayName: null },
  { handle: 'gunner23.sfproject.net', displayName: 'Maggie DuBuque' },
  { handle: 'phoebe80.sfproject.net', displayName: null },
  { handle: 'cory-cruickshank.sfproject.net', displayName: null },
  { handle: 'conor-price.sfproject.net', displayName: 'Ralph Daugherty III' },
  { handle: 'rae91.sfproject.net', displayName: null },
  { handle: 'abigale-cronin.sfproject.net', displayName: null },
  { handle: 'aileen-reilly90.sfproject.net', displayName: 'Charles Stanton' },
  { handle: 'adrianna-hansen6.sfproject.net', displayName: 'Elbert Langworth IV' },
  { handle: 'pierre54.sfproject.net', displayName: null },
  { handle: 'jaida-stark62.sfproject.net', displayName: 'Justin Stoltenberg MD' },
  { handle: 'wade-witting.sfproject.net', displayName: null },
  { handle: 'yvonne-predovic5.sfproject.net', displayName: 'Gregory Hamill' },
  { handle: 'spencer-dubuque.sfproject.net', displayName: null },
  { handle: 'randi44.sfproject.net', displayName: null },
  { handle: 'maye-grimes.sfproject.net', displayName: null },
  { handle: 'margarette-effertz.sfproject.net', displayName: null },
  { handle: 'aimee98.sfproject.net', displayName: null },
  { handle: 'jaren-veum0.sfproject.net', displayName: 'Dr. Omar Wolff' },
  { handle: 'ariel-abbott54.sfproject.net', displayName: 'Emanuel Powlowski' },
  { handle: 'mercedes23.sfproject.net', displayName: null },
  { handle: 'jarrett-orn.sfproject.net', displayName: null },
  { handle: 'damion88.sfproject.net', displayName: null },
  { handle: 'nayeli-koss73.sfproject.net', displayName: 'Johnny Lang' },
  { handle: 'cara-wiegand69.sfproject.net', displayName: null },
  { handle: 'gideon-ohara51.sfproject.net', displayName: null },
  { handle: 'carolina-mcderm77.sfproject.net', displayName: 'Latoya Windler' },
  { handle: 'danyka90.sfproject.net', displayName: 'Hope Kub' },
]
